version: '3'
services:
  web:
    build: .
    ports:
      - "5173:5173" 
    environment:
      - MONGO_URL=mongodb://mongo:27017/userDataBase # 在应用中连接 MongoDB
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017" # 映射主机的 27017 端口到容器的 27017 端口
