version: '3'
services:
  frontend:
    build: 
      context: ./frontend  # 前端项目目录
    ports:
      - "80:80"  # 将容器的 80 端口映射到主机的 80 端口
    networks:
      - kanban-network

  backend:
    build: 
      context: ./backend  # 后端项目目录
    ports:
      - "7001:7001"  # 将容器的 7001 端口映射到主机的 7001 端口
    environment:
      MONGO_URL_USER: mongodb://kanban-mongo:27017/userDataBase
      MONGO_URL_PROJECT: mongodb://kanban-mongo:27017/projectDataBase
    networks:
      - kanban-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: kanban-mongo
    ports:
      - "27017:27017"  # 将容器的 27017 端口映射到主机的 27017 端口
    volumes:
      - mongo_data:/data/db
    networks:
      - kanban-network

  mongo-init:
    image: mongo:latest
    container_name: mongo-init
    command: >
      sh -c "
      echo 'Waiting for MongoDB to be ready...';
      sleep 10;
      mongo < /docker-entrypoint-initdb.d/init-mongo.js
      "
    networks:
      - kanban-network
    depends_on:
      - mongo

networks:
  kanban-network:
    driver: bridge

volumes:
  mongo_data:
